/* eslint-disable no-console */
import { showLogger } from '@/constant/env';

/**
 * A logger function that will only logs on development
 * @param object - The object to log
 * @param comment - Autogenerated with `lg` snippet
 */
export default function logger(object: unknown, comment?: string): void {
  if (!showLogger) return;
  if (typeof window === 'undefined')
    console.log(
      '%c ============== INFO LOG \n',
      'color: #22D3EE',
      `=== ${comment ?? ''}\n`,
      object
    );
  else
    console.log(
      '%c ============== INFO LOG \n',
      'color: #22D3EE',
      `${window?.location.pathname}\n`,
      `=== ${comment ?? ''}\n`,
      object
    );
}
